[win]
192.168.1.101
192.168.1.100

[win:vars]
ansible_connection=winrm
ansible_port=5985
ansible_user=Admin
ansible_password=eve@123

[winsrv]
192.168.1.102

[winsrv:vars]
ansible_connection=winrm
ansible_port=5985
ansible_user=Administrator
ansible_password=eve@123

[pfsense]
192.168.1.1

[pfsense:vars]
ansible_connection=ssh
ansible_user=admin
ansible_password=pfsense