- name: 01_Windows_Check
  hosts: win, winsrv
  gather_facts: False

  tasks:

  - name: Ping Check
    win_ping:

  - name: Domain Member Check
    ansible.windows.win_powershell:
      script: |
        (gwmi win32_computersystem).partofdomain
        (gwmi win32_computersystem).domain
        $Ansible.Changed = $false
    register: domain
    failed_when:
      - domain.output[0] != true

  - name: Print Domain Name
    debug:
      msg: Domain name is {{ domain.output[1] }}

  - name: DisableCMD / DisableRegistry GPO Check
    ansible.windows.win_powershell:
      script: |
        gpresult /Z | Select-String "{{ item }}" -Context 1,2
        $Ansible.Changed = $false
    register: gpresult
    vars:
      ansible_become: true
      ansible_become_method: runas
      ansible_become_user: "{{ domain.output[1] }}\\{{ domain_admin_user }}"
      ansible_become_password: "{{ domain_admin_pass }}"
    failed_when:
      - "'disabled' in gpresult.output[0].Context.PostContext"
    loop:
      - DisableCMD
      - DisableRegistry
    
  - name: Print GPO Check Result
    debug:
      msg:
        - "{{ item.output[0].Context.PreContext }}"
        - "{{ item.output[0].Line }}"
        - "{{ item.output[0].Context.PostContext }}"
    loop: "{{ gpresult.results }}"
    loop_control:
      label: "{{ item.item }}"