- name: FW-2 Check
  hosts: fw2
  gather_facts: False

  tasks:

  - name: Ping Check
    ping:

  - name: General Setup Check
    pfsensible.core.pfsense_setup:
      hostname: "FW-2"
      domain: yargu
      dns_hostnames: 8.8.8.8
      timezone: Europe/Moscow

  - name: DMZ(WAN) Interface Check
    pfsensible.core.pfsense_interface:
      interface: "em0"
      descr: "DMZ"
      enable: True
      ipv4_type: "static"
      ipv4_address: "{{fw2_dmz_ip}}"
      ipv4_prefixlen: 24
      ipv4_gateway: "WANGW"
      blockbogons: False
      blockpriv: False

  - name: LAN Interface Check
    pfsensible.core.pfsense_interface:
      interface: "em1"
      descr: "LAN"
      enable: True
      ipv4_type: "static"
      ipv4_address: "{{fw2_lan_ip}}"
      ipv4_prefixlen: 24
    register: lan_cfg

  - name: Some help
    debug:
      msg:
        - "Please do \"Save -> Apply\" on LAN interface to pass this check!"
        - "P.S. This happens because after initial setup through CLI, checker can't validate that some values are default."
        - "If you still see this message, that means there is a mistake in interface configuration."
        - "{{ lan_cfg }}"
    when: lan_cfg.commands|length != 0

  - name: Gateway Check
    pfsensible.core.pfsense_gateway:
      interface: "DMZ"
      name: "WANGW"
      gateway: "{{fw1_dmz_ip}}"
      descr: "Interface wan Gateway"

  - name: Default Gateway Check
    pfsensible.core.pfsense_default_gateway:
      gateway: "WANGW"
      ipprotocol: "inet"

  - name: Disable NAT Check
    shell: |
      cat /cf/conf/config.xml | grep "<outbound>" -A 2
    register: nat_outbound
    check_mode: false
    changed_when: false
    failed_when:
      - "'disabled' not in nat_outbound.stdout_lines[1]"

  - name: DHCP Range Check
    shell: |
      cat /cf/conf/config.xml | grep "<dhcpd>" -A 8
    register: dhcpd
    check_mode: false
    changed_when: false
    failed_when:
      - "'10.10.20.10' not in dhcpd.stdout_lines[4]"
      - "'10.10.20.100' not in dhcpd.stdout_lines[5]"