- name: LAN (Win7) Check
  hosts: lan-win7
  gather_facts: False

  tasks:

  - name: Ping Check
    win_ping:

  - name: ICMP Check
    check_mode: False
    changed_when: False
    ansible.windows.win_powershell:
      script: |
        if (Test-Connection -ComputerName 8.8.8.8 -Count 4 -Quiet) {
            Write-Output "yes"
        } else {
            Write-Output "no"
        }
    register: icmp
    failed_when:
      - "icmp.output[0] == 'no'"

  - name: HTTP Check
    check_mode: False
    changed_when: False
    ansible.windows.win_uri:
      url: http://188.40.167.82/
      method: GET
      timeout: 10
      validate_certs: no
    register: http
    failed_when:
      - "http.status_code != none"

  - name: DNS Check
    check_mode: False
    changed_when: False
    ansible.windows.win_powershell:
      script: |
        nslookup ya.ru
    register: dns
    failed_when:
      - "'DNS request timed out.' not in dns.output"