- name: ICMP-SRV Check
  hosts: lan-win7
  gather_facts: False

  tasks:

  - name: Ping Check
    win_ping:

  - name: Ping Google DNS Check
    check_mode: False
    changed_when: False
    ansible.windows.win_powershell:
      script: |
        if (Test-Connection -ComputerName 8.8.8.8 -Count 4 -Quiet) {
            Write-Output "yes"
        } else {
            Write-Output "no"
        }
    register: icmp
    failed_when:
      - "icmp.output == 'no'"

  - name: Internet Access Check
    check_mode: False
    changed_when: False
    ansible.windows.win_powershell:
      script: |
        add-type @"
        using System.Net;
        using System.Security.Cryptography.X509Certificates;
        public class TrustAllCertsPolicy : ICertificatePolicy {
        public bool CheckValidationResult(
        ServicePoint srvPoint, X509Certificate certificate,
        WebRequest request, int certificateProblem) {
        return true;
        }
        }
        "@
        $AllProtocols = [System.Net.SecurityProtocolType]'Ssl3,Tls,Tls11,Tls12'
        [System.Net.ServicePointManager]::SecurityProtocol = $AllProtocols
        [System.Net.ServicePointManager]::CertificatePolicy = New-Object TrustAllCertsPolicy
        try {
            $response = Invoke-WebRequest -Uri "http://188.40.167.82/" -UseBasicParsing -TimeoutSec 5
            if ($response.StatusCode -eq 200) {
                Write-Output "yes"
            } else {
                Write-Output "no"
            }
        } catch {
            Write-Output "no"
        }
    register: http
    failed_when:
      - "http.output == 'yes'"