- name: FW-1 Check
  hosts: fw1
  gather_facts: False

  tasks:

  - name: Ping Check
    ping:

  - name: General Setup Check
    pfsensible.core.pfsense_setup:
      hostname: "FW-1"
      domain: "yargu"
      dns_hostnames: 8.8.8.8
      timezone: Europe/Moscow

  - name: WAN Interface Check
    pfsensible.core.pfsense_interface:
      interface: "em0"
      descr: "WAN"
      enable: True
      ipv4_type: "dhcp"
      blockbogons: False
      blockpriv: False
    register: wan_cfg
    changed_when:
      - wan_cfg.commands[0] != "update interface 'WAN' set ipv6_address=none"

  - name: LAN Interface Check
    pfsensible.core.pfsense_interface:
      interface: "em1"
      descr: "LAN"
      enable: True
      ipv4_type: "static"
      ipv4_address: "{{fw1_lan_ip}}"
      ipv4_prefixlen: 24
    register: lan_cfg

  - name: Some help
    debug:
      msg:
        - "Please do \"Save -> Apply\" on LAN interface to pass this check!"
        - "P.S. This happens because after initial setup through CLI, checker can't validate that some values are default."
        - "If you still see this message, that means there is a mistake in interface configuration."
        - "{{ lan_cfg }}"
    when: lan_cfg.commands|length != 0

  - name: DHCP Range Check
    check_mode: False
    changed_when: False
    shell: |
      xmllint --xpath '/pfsense/dhcpd/lan/range/*' /cf/conf/config.xml
    register: dhcpd
    failed_when:
      - "'<from>10.10.10.10</from>' not in dhcpd.stdout_lines"
      - "'<to>10.10.10.100</to>' not in dhcpd.stdout_lines"

  - name: LAN Net Alias Check
    pfsensible.core.pfsense_alias:
      name: "LAN_net"
      descr: "LAN"
      type: "network"
      address: 10.10.10.0/24
      state: present
    register: lan_alias
    changed_when:
      - lan_alias.commands[0] != "update alias 'LAN_net' set detail=none"

  - name: Allow From LAN Rule Check
    pfsensible.core.pfsense_rule:
      name: "Allow from LAN"
      protocol: any
      source: "LAN_net"
      destination: any
      interface: "LAN"

  - name: Other Rules Disabled Check
    pfsensible.core.pfsense_rule:
      name: "{{ item }}"
      interface: "LAN"
      disabled: true
      source: "NET:LAN"
      destination: any
      ipprotocol: "{{ 'inet6' if 'IPv6' in item else 'inet' }}"
    register: default_rule
    changed_when:
      - default_rule.commands[0] != "update rule '{{item}}' on 'LAN' set statetype='keep state'"
    loop:
      - "Default allow LAN to any rule"
      - "Default allow LAN IPv6 to any rule"
    loop_control:
      label: "{{ item }}"

  - name: L2TP Settings Check
    check_mode: False
    changed_when: False
    shell: |
      xmllint --xpath '/pfsense/l2tp/*' /cf/conf/config.xml
    register: l2tp_settings
    failed_when:
      - "'<localip>10.10.20.254</localip>' not in l2tp_settings.stdout"
      - "'<remoteip>10.10.20.0</remoteip>' not in l2tp_settings.stdout"
      - "'<l2tp_subnet>24</l2tp_subnet>' not in l2tp_settings.stdout"
      - "'<dns1>10.10.10.1</dns1>' not in l2tp_settings.stdout"
      - "'<dns2>8.8.8.8</dns2>' not in l2tp_settings.stdout"

  - name: L2TP Users Check
    check_mode: False
    changed_when: False
    shell: |
      xmllint --xpath '/pfsense/l2tp/user/*' /cf/conf/config.xml
    register: l2tp_users
    failed_when:
      - "'<name>user1</name>' not in l2tp_users.stdout"
      - "'<name>user1</name>' not in l2tp_users.stdout"
      - "'<password><![CDATA[eve@123]]></password>' not in l2tp_users.stdout"
      - "l2tp_users.stdout_lines|count != 6"

  - name: IPSEC Client Settings Check
    check_mode: False
    changed_when: False
    shell: |
      xmllint --xpath '/pfsense/ipsec/client/*' /cf/conf/config.xml
    register: ipsec_clients
    failed_when:
      - "'<enable/>' not in ipsec_clients.stdout"
      - "'<user_source>Local Database</user_source>' not in ipsec_clients.stdout"

  - name: IPSEC Phase1 Settings Check
    check_mode: False
    changed_when: False
    shell: |
      xmllint --xpath '/pfsense/ipsec/phase1/*' /cf/conf/config.xml
    register: ipsec_phase1
    failed_when:
      - "'<iketype>ikev1</iketype>' not in ipsec_phase1.stdout"
      - "'<mode>main</mode>' not in ipsec_phase1.stdout"

  - name: IPSEC Phase2 Encryption Settings Check
    check_mode: False
    changed_when: False
    shell: |
      xmllint --xpath '/pfsense/ipsec/phase2/encryption-algorithm-option/*' /cf/conf/config.xml
    register: ipsec_phase2_enc
    failed_when:
      - "'<name>aes</name>' not in ipsec_phase2_enc.stdout"
      - "'<keylen>128</keylen>' not in ipsec_phase2_enc.stdout"
      - "ipsec_phase2_enc.stdout_lines|count != 2"

  - name: IPSEC Phase2 Hash Settings Check
    check_mode: False
    changed_when: False
    shell: |
      xmllint --xpath '/pfsense/ipsec/phase2/hash-algorithm-option' /cf/conf/config.xml
    register: ipsec_phase2_hash
    failed_when:
      - "'<hash-algorithm-option>hmac_sha1</hash-algorithm-option>' != ipsec_phase2_hash.stdout"
      - "ipsec_phase2_hash.stdout_lines|count != 1"

  - name: IPSEC PSK Settings Check
    check_mode: False
    changed_when: False
    shell: |
      xmllint --xpath '/pfsense/ipsec/mobilekey/pre-shared-key' /cf/conf/config.xml
    register: ipsec_psk
    failed_when:
      - "'<pre-shared-key>eve@123</pre-shared-key>' != ipsec_psk.stdout"

  - name: IPSec Rule Check
    pfsensible.core.pfsense_rule:
      name: "IPSec Rule"
      protocol: udp
      source: any
      source_port: 1701
      destination: "IP:WAN"
      interface: "IPSec"

  - name: WAN Rule Check
    pfsensible.core.pfsense_rule:
      name: "WAN Rule"
      protocol: udp
      source: any
      destination: "IP:WAN"
      destination_port: 1701
      interface: "WAN"

  - name: L2TP Rule Check
    check_mode: False
    changed_when: False
    shell: |
      xmllint --xpath '/pfsense/filter/rule/*' /cf/conf/config.xml | grep "l2tp" -B 3 -A 25
    register: rules
    failed_when:
      - "'<interface>l2tp</interface>' not in rules.stdout_lines"
      - "'<type>pass</type>' not in rules.stdout_lines"
      - "'<source>\n\t\t\t\t<any/>\n\t\t\t</source>' not in rules.stdout"
      - "'<destination>\n\t\t\t\t<any/>\n\t\t\t</destination>' not in rules.stdout"
      - "'<descr><![CDATA[L2TP Rule]]></descr>' not in rules.stdout"