- name: Linux Base Setup Check
  hosts: web, reverseproxy
  gather_facts: False

  tasks:

  - name: Ping Check
    ping:

  - name: Hostname Check
    check_mode: False
    changed_when: False
    shell: hostname
    register: hostname
    failed_when:
      - "hostname.stdout | lower != inventory_hostname"
  
  - name: Interface Settings Check
    check_mode: False
    changed_when: False
    shell: cat /etc/network/interfaces
    register: interfaces
    failed_when:
      - "'auto ens3' not in interfaces.stdout_lines"
      - "'iface ens3 inet static' not in interfaces.stdout_lines"
      - "'address '+hostvars[inventory_hostname].ansible_host+'/24' not in interfaces.stdout_lines"
      - "'gateway '+hostvars['fw1'].fw1_lan_ip not in interfaces.stdout_lines"

  - name: /etc/hosts Check
    check_mode: False
    changed_when: False
    shell: cat /etc/hosts
    register: hosts
    failed_when:
      - 'inventory_hostname not in hosts.stdout | lower | regex_search("127.0.1.1[ \\t](.*)\\n", "\\1")'

  - name: /etc/resolv.conf Check
    check_mode: False
    changed_when: False
    shell: cat /etc/resolv.conf
    register: resolv
    failed_when:
      - "'nameserver 8.8.8.8' not in resolv.stdout_lines"