- name: Web Check
  hosts: wan-kali
  gather_facts: False

  tasks:

  - name: Ping Check
    ping:

  - name: /etc/hosts Check
    check_mode: False
    changed_when: False
    shell: cat /etc/hosts
    register: hosts
    failed_when:
      - 'hostvars["fw1"].fw1_wan_ip not in hosts.stdout | regex_search("\\n(.*)[ \\t]ya-fake.ru", "\\1")'
      - 'hostvars["fw1"].fw1_wan_ip not in hosts.stdout | regex_search("\\n(.*)[ \\t]mail-fake.ru", "\\1")'
      - 'hostvars["fw1"].fw1_wan_ip not in hosts.stdout | regex_search("\\n(.*)[ \\t]uniyar-fake.yargu.hack", "\\1")'

  - name: Request Check
    check_mode: False
    changed_when: False
    uri: 
      url: "http://{{ item }}"
      method: GET
    loop:
      - "ya-fake.ru"
      - "mail-fake.ru"
      - "uniyar-fake.yargu.hack"
    loop_control:
      label: "{{ item }}"
    register: result
    failed_when: "result.status != 200"