- name: Web Check
  hosts: wan-kali
  gather_facts: False

  tasks:

  - name: Ping Check
    ping:

  - name: /etc/hosts Check
    check_mode: False
    changed_when: False
    shell: cat /etc/hosts
    register: hosts
    failed_when:
      - "hostbars['fw1'].fw1_wan_ip+' ya-fake.ru' not in hosts.stdout_lines"
      - "hostbars['fw1'].fw1_wan_ip+' mail-fake.ru' not in hosts.stdout_lines"
      - "hostbars['fw1'].fw1_wan_ip+' uniyar-fake.yargu.hack' not in hosts.stdout_lines"

  - name: Request Check
    uri: 
      url: "http://{{ item }}"
      method: GET
    loop:
      - "ya-fake.ru"
      - "mail-fake.ru"
      - "uniyar-fake.yargu.hack"
    loop_control:
      label: "{{ item }}"
    register: result
    failed_when: "result.status_code != 200"