- name: Web Check
  hosts: web
  gather_facts: False

  tasks:

  - name: Ping Check
    ping:

  - name: Packets Installation Check
    check_mode: False
    changed_when: False
    shell: which whet nginx openssl
    register: which
    failed_when:
      - "which.stdout_lines | count != 3"
      - "'/usr/bin/wget' not in which.stdout_lines"
      - "'/usr/sbin/nginx' not in which.stdout_lines"
      - "'/usr/bin/openssl' not in which.stdout_lines"

  - name: Downloaded Sources Check
    check_mode: False
    changed_when: False
    shell: ls /var/www/
    register: ls
    failed_when:
      - "inventory_hostname == 'web-1' and 'ya.ru' not in ls.stdout_lines"
      - "inventory_hostname == 'web-2' and 'mail.ru' not in ls.stdout_lines"
      - "inventory_hostname == 'web-3' and 'uniyar.ac.ru' not in ls.stdout_lines"

  - name: Nginx Default Config Check
    check_mode: False
    changed_when: False
    shell: cat /etc/nginx/sites-enables/default | egrep "root|index"
    register: nginx_default
    failed_when:
      - "inventory_hostname == 'web-1' and 'ya.ru' not in nginx_default.stdout_lines"
      - "inventory_hostname == 'web-2' and 'mail.ru' not in nginx_default.stdout_lines"
      - "inventory_hostname == 'web-3' and 'uniyar.ac.ru' not in nginx_default.stdout_lines"