- name: pfSense Check
  hosts: fw1
  gather_facts: False

  tasks:

  - name: Ping Check
    ping:

  - name: General Setup Check
    pfsensible.core.pfsense_setup:
      hostname: "FW-1"
      domain: "yargu"
      dns_addresses: 8.8.8.8
      timezone: Europe/Moscow

  - name: WAN Interface Check
    pfsensible.core.pfsense_interface:
      interface: "em0"
      descr: "WAN"
      enable: True
      ipv4_type: "DHCP"
      blockbogons: False
      blockpriv: False

  - name: DMZ(LAN) Interface Check
    pfsensible.core.pfsense_interface:
      interface: "em1"
      descr: "DMZ"
      enable: True
      ipv4_type: "static"
      ipv4_address: "10.10.10.254"
      ipv4_prefixlen: 24
      ipv4_gateway: "WANGW"
      blockbogons: False
      blockpriv: False

  - name: Gateway Check
    pfsensible.core.pfsense_gateway:
      interface: "DMZ"
      name: "LAN_GW"
      gateway: 10.10.10.1
      descr: "10 to 20"

  - name: Default Gateway Check
    pfsensible.core.pfsense_default_gateway:
      gateway: "WAN_DHCP"
      ipprotocol: "inet"

  - name: Static Route Check
    pfsensible.core.pfsense_route:
      descr: "10 to 20"
      gateway: "LAN_GW"
      network: 10.10.20.0/24
      state: present

  - name: LAN Net Alias Check
    pfsensible.core.pfsense_alias:
      name: "LAN_net"
      desr: "LAN"
      type: "network"
      address: 10.10.20.0/24
      state: present

  - name: DMZ Net Alias Check
    pfsensible.core.pfsense_alias:
      name: "DMZ_net"
      desr: "DMZ"
      type: "network"
      address: 10.10.10.0/24
      state: present

  - name: Allow From LAN Rule Check
    pfsensible.core.pfsense_alias:
      name: "Allow from LAN"
      protocol: any
      source: "LAN_net"
      interface: "DMZ"

  - name: Allow From DMZ Rule Check
    pfsensible.core.pfsense_alias:
      name: "Allow from DMZ"
      protocol: any
      source: "DMZ_net"
      interface: "DMZ"

  - name: Other Rules Disabled Check
    pfsensible.core.pfsense_alias:
      name: "{{ item }}"
      interface: "DMZ"
    loop:
      - "Default allow LAN to any rule"
      - "Default allow LAN IPv6 to any rule"
    loop_control:
      label: "{{ item }}"