- name: FW-2 Check
  hosts: fw2
  gather_facts: False

  tasks:

  - name: Ping Check
    ping:

  - name: General Setup Check
    pfsensible.core.pfsense_setup:
      hostname: "FW-2"
      domain: yargu
      dns_hostnames: 8.8.8.8
      timezone: Europe/Moscow

  - name: DMZ(WAN) Interface Check
    pfsensible.core.pfsense_interface:
      interface: "em0"
      descr: "DMZ"
      enable: True
      ipv4_type: "static"
      ipv4_address: "10.10.10.1"
      ipv4_prefixlen: 24
      ipv4_gateway: "WANGW"
      blockbogons: False
      blockpriv: False

# TODO: fix problems (...)
  - name: LAN Interface Check
    pfsensible.core.pfsense_interface:
      interface: "em1"
      descr: "LAN"
      enable: True
      ipv4_type: "static"
      ipv4_address: "10.10.20.254"
      ipv4_prefixlen: 24
      blockbogons: False
      blockpriv: False

  - name: Gateway Check
    pfsensible.core.pfsense_gateway:
      interface: "DMZ"
      name: "WANGW"
      gateway: 10.10.10.254
      descr: "Interface wan Gateway"

  - name: Default Gateway Check
    pfsensible.core.pfsense_default_gateway:
      gateway: "WANGW"
      ipprotocol: "inet"

# Сделать через файл /cf/conf/config.xml
#<outbound>
#  <mode>disabled</mode>
#</outbound>
#  - name: Disable NAT Check
#    pfsensible.core.pfsense_nat_outbound:
#      nonat: true