mapping = [
    # 01 Windows
    {
        'fw1_lan_ip': '',
        'pfsense_user': '',
        'pfsense_pass': '',
        'winsrv_ip': '',
        'winsrv_user': '',
        'winsrv_pass': '',
        'win7_ip': '',
        'win10_ip': '',
        'win_user': '',
        'win_pass': '',
        'user1': '',
        'pass1': '',
        'user2': '',
        'pass2': '',
    },
    # 02 Windows Monitoring
    {},
    # 03 PfSense Base Scheme
    {
        'fw1_dmz_ip': '',
        'fw2_lan_ip': '',
        'fw2_dmz_ip': '',
        'pfsense_user': '',
        'pfsense_pass': '',
        'lan_win7_ip': '',
        'windows_user': '',
        'windows_password': '',
    },
    # 04 ICMP Tunnel
    {
        'fw1_dmz_ip': '',
        'fw2_lan_ip': '',
        'fw2_dmz_ip': '',
        'pfsense_user': '',
        'pfsense_pass': '',
        'lan_kali_ip': '',
        'linux_user': '',
        'linux_password': '',
        'lan_win7_ip': '',
        'windows_user': '',
        'windows_password': '',
    },
    # 05 DNS Tunnel
    {
        'fw1_dmz_ip': '',
        'fw2_lan_ip': '',
        'fw2_dmz_ip': '',
        'pfsense_user': '',
        'pfsense_pass': '',
        'lan_kali_ip': '',
        'linux_user': '',
        'linux_password': '',
        'lan_win7_ip': '',
        'windows_user': '',
        'windows_password': '',
        'lan_win_dns_ip': '',
        'wan_win_dns_ip': '',
        'windows_server_user': '',
        'windows_server_password': '',
    },
    # 06 VPN PfSense
    {
        'fw1_lan_ip': '',
        'pfsense_user': '',
        'pfsense_pass': '',
        'wan_win7_ip': '',
        'wan_win10_ip': '',
        'windows_user': '',
        'windows_password': '',
        'winserver_ip': '',
        'windows_server_user': '',
        'windows_server_password': '',
    },
]